#
# Licensed to Cloudkick, Inc ('Cloudkick') under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# Cloudkick licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

Import("env")
source = Split("""
nodules-server/entry.js
services/http.js
services/indexer.js
services/source_downloader.js
services/http/authors.js
services/http/categories.js
services/http/index.js
services/http/media.js
services/http/module.js
services/http/templates.js
services/source_downloader.js
util/config.js
util/getopt.js
util/log.js
util/misc.js
util/pubsub.js
util/version.js
""")
source = [env.File(x) for x in source]
Return("source")
